//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raagam.MVC.TextileManagement.UI.ProductionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductionService.IProduction")]
    public interface IProduction {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduction/GetOrderDetails", ReplyAction="http://tempuri.org/IProduction/GetOrderDetailsResponse")]
        Raagam.TextileManagement.Model.FabricCuttingChartModel GetOrderDetails(long OrderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduction/SaveFabricCuttingChart", ReplyAction="http://tempuri.org/IProduction/SaveFabricCuttingChartResponse")]
        Raagam.TextileManagement.CommonUtility.EnumConstants.SaveStatus SaveFabricCuttingChart(Raagam.TextileManagement.Model.FabricCuttingChartModel fabricCuttingChartModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductionChannel : Raagam.MVC.TextileManagement.UI.ProductionService.IProduction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductionClient : System.ServiceModel.ClientBase<Raagam.MVC.TextileManagement.UI.ProductionService.IProduction>, Raagam.MVC.TextileManagement.UI.ProductionService.IProduction {
        
        public ProductionClient() {
        }
        
        public ProductionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Raagam.TextileManagement.Model.FabricCuttingChartModel GetOrderDetails(long OrderNumber) {
            return base.Channel.GetOrderDetails(OrderNumber);
        }
        
        public Raagam.TextileManagement.CommonUtility.EnumConstants.SaveStatus SaveFabricCuttingChart(Raagam.TextileManagement.Model.FabricCuttingChartModel fabricCuttingChartModel) {
            return base.Channel.SaveFabricCuttingChart(fabricCuttingChartModel);
        }
    }
}
