//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raagam.MVC.TextileManagement.UI.ProductionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductionService.IProduction")]
    public interface IProduction {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduction/GetOrderDetails", ReplyAction="http://tempuri.org/IProduction/GetOrderDetailsResponse")]
        Raagam.TextileManagement.Model.FabricCuttingChartModel GetOrderDetails(long OrderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduction/SaveFabricCuttingChart", ReplyAction="http://tempuri.org/IProduction/SaveFabricCuttingChartResponse")]
        Raagam.TextileManagement.CommonUtility.EnumConstants.SaveStatus SaveFabricCuttingChart(Raagam.TextileManagement.Model.FabricCuttingChartModel fabricCuttingChartModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduction/DeptPurReqPopulateDropDown", ReplyAction="http://tempuri.org/IProduction/DeptPurReqPopulateDropDownResponse")]
        Raagam.TextileManagement.Model.DepartmentPurchaseRequisitionHeaderModel DeptPurReqPopulateDropDown();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduction/SaveDepartmentPurchaseRequisition", ReplyAction="http://tempuri.org/IProduction/SaveDepartmentPurchaseRequisitionResponse")]
        Raagam.TextileManagement.Model.DepartmentPurchaseRequisitionHeaderModel SaveDepartmentPurchaseRequisition(Raagam.TextileManagement.Model.DepartmentPurchaseRequisitionHeaderModel departmentPurchaseRequisitionHeaderModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduction/SelectDepartmentPurchaseRequisition", ReplyAction="http://tempuri.org/IProduction/SelectDepartmentPurchaseRequisitionResponse")]
        Raagam.TextileManagement.Model.DepartmentPurchaseRequisitionHeaderModel SelectDepartmentPurchaseRequisition(long departmentPurchaseRequisitionNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduction/GeneralDepartmentPurReqPopulateDropDown", ReplyAction="http://tempuri.org/IProduction/GeneralDepartmentPurReqPopulateDropDownResponse")]
        Raagam.TextileManagement.Model.GeneralDepartmentPurchaseRequisitionHeaderModel GeneralDepartmentPurReqPopulateDropDown();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduction/SaveGeneralDepartmentPurchaseRequisition", ReplyAction="http://tempuri.org/IProduction/SaveGeneralDepartmentPurchaseRequisitionResponse")]
        Raagam.TextileManagement.Model.GeneralDepartmentPurchaseRequisitionHeaderModel SaveGeneralDepartmentPurchaseRequisition(Raagam.TextileManagement.Model.GeneralDepartmentPurchaseRequisitionHeaderModel departmentPurchaseRequisitionHeaderModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduction/SelectGeneralDepartmentPurchaseRequisition", ReplyAction="http://tempuri.org/IProduction/SelectGeneralDepartmentPurchaseRequisitionResponse" +
            "")]
        Raagam.TextileManagement.Model.GeneralDepartmentPurchaseRequisitionHeaderModel SelectGeneralDepartmentPurchaseRequisition(long departmentPurchaseRequisitionNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduction/SelectProductGrid", ReplyAction="http://tempuri.org/IProduction/SelectProductGridResponse")]
        System.Collections.Generic.List<Raagam.TextileManagement.Model.SelectProductGridModel> SelectProductGrid(long SupplierSequenceNumber, string ProductName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductionChannel : Raagam.MVC.TextileManagement.UI.ProductionService.IProduction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductionClient : System.ServiceModel.ClientBase<Raagam.MVC.TextileManagement.UI.ProductionService.IProduction>, Raagam.MVC.TextileManagement.UI.ProductionService.IProduction {
        
        public ProductionClient() {
        }
        
        public ProductionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Raagam.TextileManagement.Model.FabricCuttingChartModel GetOrderDetails(long OrderNumber) {
            return base.Channel.GetOrderDetails(OrderNumber);
        }
        
        public Raagam.TextileManagement.CommonUtility.EnumConstants.SaveStatus SaveFabricCuttingChart(Raagam.TextileManagement.Model.FabricCuttingChartModel fabricCuttingChartModel) {
            return base.Channel.SaveFabricCuttingChart(fabricCuttingChartModel);
        }
        
        public Raagam.TextileManagement.Model.DepartmentPurchaseRequisitionHeaderModel DeptPurReqPopulateDropDown() {
            return base.Channel.DeptPurReqPopulateDropDown();
        }
        
        public Raagam.TextileManagement.Model.DepartmentPurchaseRequisitionHeaderModel SaveDepartmentPurchaseRequisition(Raagam.TextileManagement.Model.DepartmentPurchaseRequisitionHeaderModel departmentPurchaseRequisitionHeaderModel) {
            return base.Channel.SaveDepartmentPurchaseRequisition(departmentPurchaseRequisitionHeaderModel);
        }
        
        public Raagam.TextileManagement.Model.DepartmentPurchaseRequisitionHeaderModel SelectDepartmentPurchaseRequisition(long departmentPurchaseRequisitionNumber) {
            return base.Channel.SelectDepartmentPurchaseRequisition(departmentPurchaseRequisitionNumber);
        }
        
        public Raagam.TextileManagement.Model.GeneralDepartmentPurchaseRequisitionHeaderModel GeneralDepartmentPurReqPopulateDropDown() {
            return base.Channel.GeneralDepartmentPurReqPopulateDropDown();
        }
        
        public Raagam.TextileManagement.Model.GeneralDepartmentPurchaseRequisitionHeaderModel SaveGeneralDepartmentPurchaseRequisition(Raagam.TextileManagement.Model.GeneralDepartmentPurchaseRequisitionHeaderModel departmentPurchaseRequisitionHeaderModel) {
            return base.Channel.SaveGeneralDepartmentPurchaseRequisition(departmentPurchaseRequisitionHeaderModel);
        }
        
        public Raagam.TextileManagement.Model.GeneralDepartmentPurchaseRequisitionHeaderModel SelectGeneralDepartmentPurchaseRequisition(long departmentPurchaseRequisitionNumber) {
            return base.Channel.SelectGeneralDepartmentPurchaseRequisition(departmentPurchaseRequisitionNumber);
        }
        
        public System.Collections.Generic.List<Raagam.TextileManagement.Model.SelectProductGridModel> SelectProductGrid(long SupplierSequenceNumber, string ProductName) {
            return base.Channel.SelectProductGrid(SupplierSequenceNumber, ProductName);
        }
    }
}
