//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raagam.MVC.TextileManagement.UI.CommonService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommonService.ICommon")]
    public interface ICommon {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/CheckLogin", ReplyAction="http://tempuri.org/ICommon/CheckLoginResponse")]
        Raagam.TextileManagement.Model.LoginModel CheckLogin(Raagam.TextileManagement.Model.LoginModel loginModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonChannel : Raagam.MVC.TextileManagement.UI.CommonService.ICommon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonClient : System.ServiceModel.ClientBase<Raagam.MVC.TextileManagement.UI.CommonService.ICommon>, Raagam.MVC.TextileManagement.UI.CommonService.ICommon {
        
        public CommonClient() {
        }
        
        public CommonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Raagam.TextileManagement.Model.LoginModel CheckLogin(Raagam.TextileManagement.Model.LoginModel loginModel) {
            return base.Channel.CheckLogin(loginModel);
        }
    }
}
