//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raagam.MVC.TextileManagement.UI.MerchandiserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MerchandiserService.IMerchandiser")]
    public interface IMerchandiser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMerchandiser/PopulateDropDown", ReplyAction="http://tempuri.org/IMerchandiser/PopulateDropDownResponse")]
        Raagam.TextileManagement.Model.OrderMainModel PopulateDropDown(Raagam.TextileManagement.Model.OrderMainModel orderMainModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMerchandiserChannel : Raagam.MVC.TextileManagement.UI.MerchandiserService.IMerchandiser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MerchandiserClient : System.ServiceModel.ClientBase<Raagam.MVC.TextileManagement.UI.MerchandiserService.IMerchandiser>, Raagam.MVC.TextileManagement.UI.MerchandiserService.IMerchandiser {
        
        public MerchandiserClient() {
        }
        
        public MerchandiserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MerchandiserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MerchandiserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MerchandiserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Raagam.TextileManagement.Model.OrderMainModel PopulateDropDown(Raagam.TextileManagement.Model.OrderMainModel orderMainModel) {
            return base.Channel.PopulateDropDown(orderMainModel);
        }
    }
}
