//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raagam.MVC.TextileManagement.UI.MerchandiserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MerchandiserService.IMerchandiser")]
    public interface IMerchandiser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMerchandiser/PopulateDropDown", ReplyAction="http://tempuri.org/IMerchandiser/PopulateDropDownResponse")]
        Raagam.TextileManagement.Model.OrderMainModel PopulateDropDown(Raagam.TextileManagement.Model.OrderMainModel orderMainModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMerchandiser/SelectColorSize", ReplyAction="http://tempuri.org/IMerchandiser/SelectColorSizeResponse")]
        Raagam.TextileManagement.Model.OrderMainModel SelectColorSize(long StyleSequenceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMerchandiser/SaveOrder", ReplyAction="http://tempuri.org/IMerchandiser/SaveOrderResponse")]
        long SaveOrder(Raagam.TextileManagement.Model.OrderMainModel orderMainModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMerchandiser/GetOrderDetails", ReplyAction="http://tempuri.org/IMerchandiser/GetOrderDetailsResponse")]
        Raagam.TextileManagement.Model.OrderMainModel GetOrderDetails(long OrderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMerchandiser/StylePopulateDropDown", ReplyAction="http://tempuri.org/IMerchandiser/StylePopulateDropDownResponse")]
        Raagam.TextileManagement.Model.StyleListModel StylePopulateDropDown();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMerchandiser/SaveStyle", ReplyAction="http://tempuri.org/IMerchandiser/SaveStyleResponse")]
        Raagam.TextileManagement.Model.StyleListModel SaveStyle(Raagam.TextileManagement.Model.StyleModel styleModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMerchandiser/EditStyle", ReplyAction="http://tempuri.org/IMerchandiser/EditStyleResponse")]
        Raagam.TextileManagement.Model.StyleModel EditStyle(long styleSequenceNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMerchandiserChannel : Raagam.MVC.TextileManagement.UI.MerchandiserService.IMerchandiser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MerchandiserClient : System.ServiceModel.ClientBase<Raagam.MVC.TextileManagement.UI.MerchandiserService.IMerchandiser>, Raagam.MVC.TextileManagement.UI.MerchandiserService.IMerchandiser {
        
        public MerchandiserClient() {
        }
        
        public MerchandiserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MerchandiserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MerchandiserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MerchandiserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Raagam.TextileManagement.Model.OrderMainModel PopulateDropDown(Raagam.TextileManagement.Model.OrderMainModel orderMainModel) {
            return base.Channel.PopulateDropDown(orderMainModel);
        }
        
        public Raagam.TextileManagement.Model.OrderMainModel SelectColorSize(long StyleSequenceNumber) {
            return base.Channel.SelectColorSize(StyleSequenceNumber);
        }
        
        public long SaveOrder(Raagam.TextileManagement.Model.OrderMainModel orderMainModel) {
            return base.Channel.SaveOrder(orderMainModel);
        }
        
        public Raagam.TextileManagement.Model.OrderMainModel GetOrderDetails(long OrderNumber) {
            return base.Channel.GetOrderDetails(OrderNumber);
        }
        
        public Raagam.TextileManagement.Model.StyleListModel StylePopulateDropDown() {
            return base.Channel.StylePopulateDropDown();
        }
        
        public Raagam.TextileManagement.Model.StyleListModel SaveStyle(Raagam.TextileManagement.Model.StyleModel styleModel) {
            return base.Channel.SaveStyle(styleModel);
        }
        
        public Raagam.TextileManagement.Model.StyleModel EditStyle(long styleSequenceNumber) {
            return base.Channel.EditStyle(styleSequenceNumber);
        }
    }
}
